#+title: Web Security
#+SETUPFILE: /Users/visco/.config/doom/latex-standard-setup.org

* Web Sessions Security

** Session Management
1) *Server-side state*: Persist the state information on the server, e.g., in a
   database, and use the cookie just to store a session identifier. The database
   storing session information can become a bottleneck.
2) *Client-side state*: Persist the state information directly into the cookie.
   A secure implementation requires the use of cryptography, at least for
   signing the cookie and possibly for encrypting it.

** Attacks on sessions integrity

*** Session hijacking
An attacker who gets access to a honest user’s cookies can impersonate her by
presenting such cookies: this attack is known as session hijacking.

#+begin_quote
*HTTP only cookie*: Cookies marked with the HttpOnly attribute are not
 accessible to JS, thus offering confidentiality against web attackers.
#+end_quote

#+begin_quote
*Secure cookies*: Cookies marked with the Secure attribute are only sent over
 HTTPS and made inaccessible to JavaScript running in HTTP pages. The Secure
 attribute should be used even when the web application is entirely deployed
 over HTTPS.
#+end_quote

*** Session fixation
Many web applications use *pre-sessions* (unauthenticated sessions) to keep
track of state information even before login. For example, Most e-commerce
applications allow users to add items to their shopping cart before login for
usability reasons. The content of the cart is persisted upon login to enable
payments. *Cookies storing session identifiers should be refreshed every time
the privilege level of the session changes, e.g., upon login*. Otherwise, the
web application might be vulnerable to *session fixation*.

#+begin_quote
*Session fixation through cookie*: This method explores the server response to
 fix the Session ID in the victim’s browser. Including the parameter Set-Cookie
 in the HTTP header response, the attacker is able to insert the value of
 Session ID in the cookie and sends it to the victim’s browser.
#+end_quote

**** Preventing Session fixation
1) *Refresh cookies upon authentication*: when the credentials are verified,
   change the value of the cookie and start a new session;
2) *Enforce cookie integrity*: ensure that the attacker cannot set cookies for
   the target web application

*** Cross-Site-Request-Forgery
Since cookies are automatically attached to HTTP requests by default, an
attacker can *force the creation of authenticated requests from the victim’s
browser*, which might trigger security-sensitive actions (CSRF).

Discussed below in detail.

*** Cookie forcing
Cookie forcing is not necessarily dangerous, but can be nasty. *Example*: Since
paypal.com binds a credit card number to a personal account, an attacker can
perform cookie forcing on paypal.com to eventually *get access to the credit
card* number of the victim.

** Session expiration
Cookies are deleted by default when the web browser is closed, but web
applications can modify this through the *Expires* attribute:
- *long session lifetimes* improve usability, but might harm security;
- make the *“Remember Me”* functionality an opt-in.

*Implementation*:
- *Server-Side State*: Expiration is simple to implement: just invalidate the
  session identifier by deleting the corresponding entries from the database.
- *Client-Side State*: Include an expiration date as part of the encrypted data
  and implement a blacklist of session cookies issued to compromised accounts.

* Same Origin Policy (SOP)
The Same Origin Policy (SOP) is the baseline defense mechanism of web browsers,
which isolates data controlled by good.com from read / write accesses by scripts
served from evil.com.

** Web Origins
SOP defines its own isolation domains in terms of origins.

#+begin_quote
*Origin*: An origin is a triple including a scheme, a hostname and a port. When
 the port is omitted, the default port of the scheme is implicitly assumed.
#+end_quote

#+begin_quote
*SOP restrictions*: At a high level, SOP can be summarized as follows: data
 owned by origin $o_{1}$ must be isolated from read / write accesses by any
 origin $o_{2} \neq o_{1}$.
#+end_quote

** Cookies VS Web Storage

| Cookies                          | Web Storage                        |
| - Relaxed SOP (insicure)         | + Traditional SOP (more secure)    |
| - Sent automatically (CSRF)      | + Sent on demand (no CSRF)         |
| + HttpOnly: shielded from JS     | - Always accessible to JS (risky)  |
| + Sessions are easy to implement | - Sessions require custom JS logic |

*Cookies + Web Storage = Better sessions* against the Session hijacking, session
fixation, CSRF.

** SOP and content inclusion
Since the Web is designed to be interconnected, *SOP puts very little
restrictions* on content inclusion. For example, foo.com can normally load
images and stylesheets from bar.com.

#+begin_quote
*Sub-Resource Integrity*: It is possible to enforce integrity checks on included
 scripts, browsers fetching the remote script compare the hash in the integrity
 tag with the hash computed from the downloaded script; if the two hashes do not
 match, the script is not loaded. *Difficult to deploy*.
#+end_quote

** Cross-Origin-Resource-Sharing (CORS)
CORS provides a disciplined way to relax the restrictions of SOP:
1) foo.com asks for permission to read cross-origin data;
2) bar.com grants or denies such permission;
3) the browser enforces the authorization decision at foo.com;

#+begin_quote
*CORS headers*:
- *Origin*: request header containing the origin which is asking for
  cross-origin read permission;
- *Access-Control-Allow-Origin*: response header containing the origin to which
  such permission is granted (* for any origin).

  Access is granted iff the content of the Access-Control-Allow-Origin header
  matches the content of the Origin header.
#+end_quote

*** CORS: Non-Simple Requests
#+begin_quote
*CORS headers*:
- *Access-Control-Request-Method*: preflight request header containing the
  method of the non-simple request;
- *Access-Control-Request-Headers*: preflight request header containing the list
  of the custom headers of the non-simple request;
- *Access-Control-Allow-Methods*: preflight response header containing a list of
  allowed methods;
- *Access-Control-Allow-Headers*: preflight response header containing a list of
  allowed custom headers;
- *Access-Control-Max-Age*: preflight response header for caching.
#+end_quote

*** Security of CORS
CORS is a standardized, more secure alternative to JSONP:
1) *No script injection*: though the callee can still respond with arbitrary
   content, the caller can process the response (not a script) before actually
   using it. This is normally done in the XHR callback.
2) *No information leakage*: only credentialed requests might disclose
   confidential information and the callee has control over them, thanks to the
   Access-Control-Allow-Origin header.

* Cross-site scripting (XSS)
Cross Site Scripting (XSS) is the king of client-side attacks, because it allows
the attacker to inject scripts on a vulnerable web application: when a malicious
script runs in the target’s origin, *SOP is ineffective*.

*XSS flow*:
1) the attacker identifies a part of the target web application which processes
   *untrusted input from the user*, e.g., a search field;
2) the attacker discovers that the supplied *input can be eventually interpreted
   as a script*, e.g., using their own browser;
3) the attacker sends a maliciously crafted link to the victim, who accesses it
   and triggers a script injection;
4) since the script actually comes from the target web application, it runs *in
   the same origin of the target*.

** XSS Categories
#+begin_quote
*Type flow*:
- *Reflected XSS*: happens when web applications echo back untrusted user input
  to the client.
- *Persistent XSS*: happens when web applications store untrusted user input
  somewhere and automatically echo it back later.
#+end_quote

#+begin_quote
*Location of flow*:
- *Server-side XSS*: vulnerable code on the server (“traditional” XSS)
- *Client-side XSS*: vulnerable code on the client (DOM-based XSS)
#+end_quote

*** Categories summary
| *Reflected server-side XSS*                               | *Reflected client-side XSS*                               | *Persistent server-side XSS*                   | *Persistent client-side* XSS                    |
| User must visit malicious link                            | User must visit malicious link                            | Attacker can store malicious payload on server | User must visit malicious link, but just once   |
| No persistent change to the server (one attack per visit) | No persistent change to the client (one attack per visit) | Every user of the site affected on every visit | Single user of the site affected on every visit |

*** XSS Polyglot
A polyglot is an exploit working in several different contexts:
#+begin_src javascript
javascript:alert()//"){}alert();//</a><script>alert()</script>
#+end_src

** XSS defenses
| *Output encoding*                                   | *Input Sanitization*                                    |
| Very easy to use                                    | Don’t do it by yourself!                                |
| Solves the root cause of the security vulnerability | Some attacks like markup injection might still be there |
| Sometimes restrictive                               | Sometimes necessary                                     |

* Content Security Policy (CSP)
CSP was born as an industrial effort to design a *declarative client-side
defense* mechanism *against XSS* in 2010:
- Now supported by all major web browsers;
- Useful defense-in-depth (*mitigation*) approach against XSS: it does not
  substitute input sanitization and output encoding;
- No protection against scriptless attacks like HTML markup injection.

A CSP is a *page-level security policy* delivered to the browser via the
*Content-Security-Policy* header. The browser then takes care of enforcing the
policy on the page.

** CSP directives
| *Directive* | *Applies to*                |
| connect-src | Targets of XHRs             |
| img-src     | Images and favicons         |
| object-src  | Plugins (Flash, applets...) |
| script-src  | JavaScript files            |
| style-src   | CSS files                   |
| default-src | Fallback directive          |

** CSP default restrictions (script-src, default-src)
*Script execution*:
- No execution of inline scripts;
- No execution of inline event handlers, e.g., onerror;
- No execution of javascript: URLs.

*String-to-code transformation*:
- Invocation of the eval function is forbidden;
- Functions like setTimeout must be invoked with a callable.

** CSP Roadblocks
1) *Whitelist*: The simplest way to build whitelists is to enforce a restrictive
   CSP as report-only via the *Content-Security-Policy-Report-Only* header;
2) *Inline Scripts and Friends*: CSP forbids inline scripts, event handlers and
   javascript, so one has to:
   1) Move inline scripts to external files;
   2) Replace event handlers with listeners registered by external scripts;
   3) Replace javascript: URLs with script-initiated code.
3) *String-to-Code Transformations*: Functions like eval and setTimeout can be
   used to transform strings into code, thus leading to injections.

** CSP Nonces
CSP can now be used to whitelist scripts (inline or external) bearing a *valid
nonce*, i.e., a random, unpredictable string:
#+begin_src html
script-src ’self’ https://example.com ’nonce-54321’; default-src ’self’
#+end_src

Individual inline scripts can be whitelisted using the nonce attribute (the same
nonce can be used for many inline scripts):
#+begin_src html
<script nonce="54321"> alert(1); </script>
#+end_src

*Nonces advantages*:
- They provide support for inline scripts, without falling back to the complete
  absence of security of ’unsafe-inline’;
- They whitelist individual scripts as opposed to entire origins, which
  simplifies the security auditing

#+begin_quote
The developer is in charge of generating random, unpredictable nonces on each
incoming request and populating the CSP header correctly: *Nonce reuse can
easily break protection against XSS*.
#+end_quote

** Supporting dynamic scripts
Make use of the *’strict-dynamic’* keyword, which propagates trust from
nonce-authorized scripts to the new scripts they insert.

Or, *CSP hashes*: Hashes provide better security guarantees than nonces, because
they take the actual script code into account.
#+begin_src html
script-src ’sha512-YWIzOWNiNzJjNDRlY’;
#+end_src
The following inline script will be executed, under the assumption that the
SHA-512 hash of its body is YWIzOWNiNzJjNDRlY:
#+begin_src html
<script> alert(1); </script>
#+end_src

#+begin_quote
*’strict-dynamic’ also covers hash-authorized scripts*.
#+end_quote

** Summary: How to configure CSP?
1) *whitelist-based*: often *insecure*. Even assuming CSP best practices are
   followed, it is basically impossible to vet entire origins;
2) *nonce-based*: *more secure, but no guarantees* about the executed script
   content. Be aware of the dangers of ’strict-dynamic’;
3) *hash-based*: *complete control* of the executed scripts, including their
   content, but often *too complicated to deploy* in practice.


* Cross-site request forgery
CSRF is enabled by the attachment of session cookies to HTTP requests forged by
malicious pages.

** How to prevent CSRF?
- *Server-side fixes*: Do not authenticate requests based on cookies alone;
- *Client-side fixes*: Change the way cookies work: modern browsers offer a
  native protection mechanism via the *SameSite* cookie attribute.

#+begin_quote
*Referer checking*: A possible defense against CSRF is checking the content of
 the Referer header of security-sensitive HTTP requests. This header contains
 the full URL of the page which sent the request.
#+end_quote

#+begin_quote
*Origin checking*: Rather than checking the value of the Referer header, one can
 check the value of the Origin header introduced for CORS:
 - *privacy-friendly* version of Referer: it includes just the origin, not the
   entire URL;
 - always attached to XHR requests by default
 - in modern browsers: also attached to cross-origin *POST requests*, e.g., upon
   form submission

 In general, *Origin checking should be preferred over Referer checking*, but the
 two mechanisms share similar limitations.
#+end_quote

#+begin_quote
*Custom headers*: Another defense relies on custom headers, e.g., *CSRF-Protection: 1*. The presence of the header already suffices and its value is unimportant, since SOP prevents the use of custom headers on cross-origin requests.
#+end_quote

#+begin_quote
*Secret tokens*: The most common defense against CSRF deployed in the wild is the inclusion of secret tokens as part of security-sensitive requests. The expected value of the secret token is typically stored in the user’s session at the server side: only requests bearing a valid token are processed by the web application.
#+end_quote

** Double Sumbit
The *double submit pattern* is a popular approach to the use of tokens:
- the token is still embedded as a parameter of each sensitive HTTP request, as
  in the previous example, *but the right value of the token is stored inside a
    cookie* (rather than in the session);
- Every time a sensitive HTTP request is received, *the server checks that the
    value of the cookie matches the value of the parameter*;
- As before: the attacker cannot craft a request with the right value of the parameter (unless they know the value of the cookie).

*** Double Submit: Cookie confidentiality
Since the double submit pattern stores a secret token inside a cookie, the confidentiality of the cookie must be ensured:
- Mark the cookie with the *Secure* attribute to prevent its disclosure;
- Perhaps surprisingly, notice that the *HttpOnly attribute does not
  provide much help* here!

*Secure implementation*: Alternatively, adopt the Secure- prefix to ensure
cookie integrity.

** SameSite Cookies
Cookies marked with the *SameSite attribute* can be configured so that they are
not attached to cross-site requests:
- *site = registrable domain* (e.g., google.com) and its subdomains;
- *SameSite=Strict*: applies this policy to every HTTP request, thus
offering high security, but with the risk of breaking web applications
- *SameSite=Lax*: relaxes this restriction in the case of top-level navigations
  with a safe method, e.g., resulting from clicking a link

This defense is simple and effective, but it does not offer protection to legacy
browsers, hence also more traditional defenses like tokens should be
implemented.

** Vulnerability: Login CSRF
If the login form of a web application is not protected against CSRF, the
attacker can force the victim into authenticating using the attacker’s account:
this attack is known as *login CSRF*.

*Defense*:
- *header checks* upon login form submission;
- *secret tokens* in the login form: since login CSRF happens before the
  authenticated session, you must setup a pre-session for the token (commonly
  used);
- *SameSite cookies*: just require the presence of a SameSite cookie upon login
  form submission. This requires enforcing cookie integrity against network
  attackers, otherwise the cookie could be forged

** CSRF prevention: summary
1) Checking the content of the Referer / Origin header or the mere
   presence of custom headers might work, but this is often impractical;
1) Secret tokens are better for most applications, but implementation is not
   straightforward;
3) SameSite cookies are a simple and elegant solution against CSRF, which solves
   the issues of tokens, but only protects modern browsers and a part of the
   state-changing requests.

   *Best practice: SameSite cookies + secret tokens.*

** XSS vs CSRF
Both XSS and CSRF are dangerous attacks. Notice that:
- if a web application is vulnerable against XSS, none of the proposed defenses
  against CSRF is effective, because *the attacker operates from a same-site
  position*. This means that XSS is a more serious security concern than CSRF in
  most cases.

* Frames Security
A frame is a part of a web page which *renders content independently of its
container*.
It is usually used for:
- *advertisement*: content served by an advertisement network is placed in a
  separate area to generate revenue;
- *authentication*: login form of a single sign-on provider is placed in a
  separate area, which looks the same on all the including websites;
- *gadgets*: “like” buttons and such

The parent frame and its children keep *living in their own origins*.

#+begin_quote
*Prevent framing*: The operators of good.com might want to forbid framing
 content from evil.com, for example because it displays inappropriate content:
 they can do this by using the *frame-src* directive of CSP.
#+end_quote

#+begin_quote
*Prevent being framed*: The operators of good.com might want to forbid being
 framed from evil.com, for example to mitigate phishing attempts: they can do
 this by using the *X-Frame-Options* header or the *frame-ancestors* directive of
 CSP.
#+end_quote

Frames on the same origin can communicate by *reading and writing* over their
DOMs, since SOP does not isolate them.

** Domain relaxation
Frames on the same site can relax their document.domain property to get the same
origin and enable communication. $p_{1}$ at https://www.foo.com loads $p_{2}$ at
https://mail.foo.com inside a frame, then the two frames can communicate as
follows:
1) $p_{1}$ sets document.domain to foo.com;
2) $p_{2}$ sets document.domain to foo.com;
3) $p_{1}$ and $p_{2}$ now have the same origin and can communicate.

This can have security implications:

** postMessage
Frame communication between different origins is better implemented by means of
the postMessage API.

#+begin_src javascript
targetWindow.postMessage(message, targetOrigin);
#+end_src

Message reception:
#+begin_src javascript
window.addEventListener("message", receiveMessage);
#+end_src

*** postMessage: security considerations
postMessage is better than domain relaxation for frame communication, because it
is more general and exchanges serialized data *without granting scripting access*
to the frame.

** Frame sandboxing
It is possible to restrict the privileges of frames by setting the sandbox
attribute to the empty string. The most important restrictions are:
1) the content of the frame is treated as being from a *unique origin*, thus
   enforcing frame isolation thanks to SOP;
2) *form submission* from the frame is blocked;
3) all forms of *script execution* in the frame are blocked;
4) *plugin execution* in the frame is blocked;
5) *popup creation* from the frame is blocked;
6) *top-level navigation* via window.top.location is blocked.

It is possible to relax individual security restrictions:

| *Default Restriction*           | *Relaxed with*       |
| enforce unique origin           | allow-same-origin    |
| form submission is blocked      | allow-forms          |
| script execution is blocked     | allow-scripts        |
| popup creation is blocked       | allow-popups         |
| top-level navigation is blocked | allow-top-navigation |

*Example:*
#+begin_src html
<iframe src="https://platform.twitter.com/tweet_button.html"
        sandbox="allow-same-origin allow-scripts
                 allow-popups allow-forms"/>
#+end_src

** Clickjacking
Clickjacking is a UI-based attack in which a user is tricked into clicking on
actionable content on a target website by clicking on some other content in a
decoy website, operated by the attacker.

The attacker uses the opacity and z-index attributes of CSS to place a
transparent frame pointing to the target website on top of content of the decoy
website.

*Clickjacking is a great technique to bypass CSRF protection, because the request
comes from a same-site position!*

*** Solutions against clickjacking: *X-Frame-Options*
A better solution against clickjacking is based on the X-Frame-Options header
(XFO for short). It can take three possible values:
- *DENY*: page framing is denied;
- *SAMEORIGIN*: page framing is only allowed on the same origin;
- *ALLOW-FROM* $u$: page framing is only allowed at $u$

*Note that ALLOW-FROM is not supported by Chrome and derivates*.

**** Problems with XFO
#+begin_quote
*Limited Expressiveness*: XFO does not allow to express useful policies like:
- framing is allowed on any origin from a whitelist
- framing is allowed on any subdomain of a given site
#+end_quote

#+begin_quote
*Incomplete Specification*: was implemented in browsers before being
 standardized, different browsers might give different interpretations to the
 same value.
#+end_quote

**** Double Framing
The XFO specification does not mandate whether origin checks have to be
performed on the top-level browsing context or on the full chain of ancestors,
hence some browsers are subject to double framing attacks.

An attacker who exploits a markup injection at good.com can perform clickjacking
by abusing nested frames, unless the browser checks the full chain of frame
ancestors.

The *frame-ancestors* directive introduced in *CSP Level 2* is the best protection
mechanism against clickjacking on modern browsers:
- it leverages the full expressive power of the source expressions of CSP;
- it solves the issue of double framing, since all ancestors are checked
- it overrides XFO in browsers supporting CSP Level 2

** CSP vs XFO

#+begin_quote
A policy p is *security-oriented* if and only if:
- $p$ is consistent for the set of legacy browsers $B_{l}$
- $p$ is consistent for the set of legacy browsers $B_{m}$
- for any $b_{l}$ in $B_{l}$ and $b_{m}$ in $B_{m}$, the security restrictions on $b_{l}$ are no weaker than the security restrictions on $b_{m}$
#+end_quote

#+begin_quote
A policy p is *compatibility-oriented* if and only if:
- $p$ is consistent for the set of legacy browsers $B_{l}$
- $p$ is consistent for the set of legacy browsers $B_{m}$
- for any $b_{l}$ in $B_{l}$ and $b_{m}$ in $B_{m}$, the security restrictions on $b_{m}$ are no weaker than the security restrictions on $b_{l}$
#+end_quote

** SameSite Cookies and Clickjacking
*Cookies with the SameSite attribute (Strict or Lax) are not included in requests
sent from a frame embedded in a cross-site position*:
- effective against most clickjacking attempts, i.e., those abusing
  authentication to achieve *effects similar to CSRF*;
- *legacy browsers do not support the SameSite attribute*, so this can only be
  part of a defense-in-depth strategy (use XFO and CSP);
- web applications implementing authentication without using cookies, e.g., on
  top of the web storage, must still rely on *XFO and CSP to prevent clickjacking*
  attempts.

* HTTP & TLS
HTTPS is the *encrypted variant* of HTTP:
- HTTPS = HTTP on top of a cryptographic protocol (SSL / TLS);
- HTTPS provides confidentiality, integrity and server authentication
- support for client authentication, yet basically unused in practice

** TLS
- *asymmetric cryptography*: used to establish a symmetric key, called the session
  key, between the client and the server;
- *symmetric cryptography*: used to ensure the confidentiality and the integrity
  of the exchanged messages by means of the session key;
- *certificates*: used to provide authentication by binding the public key of the
  server to its identity. This is done thanks to a signature issued by a trusted
  Certification Authority (CA).

*** TLS Flow
1) The client initiates a *handshake* with the server by proposing a TLS version
   and a list of supported cipher suites (crypto algorithms);
2) The server chooses the lower between its highest supported *TLS version* and
   the TLS version proposed by the client. It then picks a supported *cipher*
   suite from the proposed list and *sends its certificate*;
3) The client confirms the validity of the certificate and retrieves the
   *server’s public key* from it;
4) The client confirms the *validity of the certificate* and retrieves the
   server’s public key from it;
5) The client and the server take appropriate actions to generate the *session
   key*, taking advantage of the server’s public key;
6) The session key is used to *protect the communication*.

*** Session key establishment: RSA
1) the client generates a random number s;
2) the client sends s to the server, encrypted with the server’s pub key;
3) the server decrypts s using its private key;
4) the client and the server generate the session key k from s, using a key
   derivation algorithm.

** Protocol downgrade attacks
Downgrade attacks are often implemented as part of a MITM attack and may be used
as a way of enabling a cryptographic attack that might not be possible
otherwise:
1) The *client initiates a handshake* with the server by proposing a TLS version
   and a list of supported cipher suites;
2) The *attacker intercepts and modifies the original message*, so that it
   contains insecure protocol versions such as TLS 1.0 and SSL 3.0;
3) The *server chooses the lower* between its highest supported *TLS version* and
   the TLS version proposed by the client. It then picks a supported cipher
   suite from the proposed list and sends its certificate;
4) If the attack is successful, *an insecure protocol or cipher suite is used*

*Mitigation techniques*:
- Disable server-side support for legacy protocols and insecure cipher suites.
  This might require fixes to other servers using the same certificate, i.e.,
  using the same private key;
- Use TLS 1.3: native protection against downgrade attacks. It is a major
  overhaul of TLS 1.2, despite the small change to the version number

** Heartbleed
Some attacks against TLS are not enabled by the protocol design, but rather by
its implementation! A famous example is the Heartbleed attack against OpenSSL.

Simple fix: *update the OpenSSL version* or at the very least disable the
Heartbeat extension upon compilation.

** Certificates
A certificate is a *cryptographic proof of the ownership of a public key*. It
contains several fields, including:
1) Serial Number: used to handle certificate revocation;
2) Subject: the owner of the public key, i.e., the server’s identity;
3) Public Key: the public key of the subject;
4) Issuer: the entity who created the certificate;
5) Validity: the validity period of the certificate;
6) Signature: a signature of the certificate body with the issuer’s private key;

#+begin_quote
A *certificate chain* is a list of certificates such that:
1) the Issuer of each certificate (except the last one) matches the Subject of
   the next certificate in the list;
2) each certificate (except the last one) can be verified using the public key
   contained in the next certificate in the list;
3) the last certificate is a trust anchor, i.e., a self-signed certificate that
   one trusts because it was issued by a trusted certification authority.
#+end_quote

*** Types of certificates
Certificates can have three different *validation levels*:
1) *Domain Validation*: bind a public key to a domain name, i.e., they are issued
   after showing the right to manage a domain name;
2) *Organization Validation*: bind a public key to an organization, i.e., they
   additionally require a proof of existence as a legal entity;
3) *Extended Validation*: similar to Organization Validation, but with even
   stricter rules aimed at assessing the legitimacy of the company.

*** Scope of certificates
1) *Single domain*: valid for a domain name and the www sub-domain;
2) *Multiple domains*: valid for an arbitrary list of domain names, set in the
   Subject Alternative Name field of the certificate;
3) *Arbitrary sub-domains*: valid for a domain name and all its first-level
   sub-domains, e.g., *.example.com.

The scope of certificates is important:
- if two machines share the same certificate, they also share the same public
  and private keys!
- once a machine is compromised and its private key is leaked, the attacker can
  impersonate all the other machines sharing the same certificate and possibly
  inspect traffic exchanged with them;
- certificate reuse increases the attack surface against web apps.

* More HTTPS

** Mixed Content Policy
The Mixed Content policy recommends defensive techniques to mitigate the dangers
of insecurely-loaded sub-resources.
- *passive content* like images, audios and videos: optionally blockable, i.e.,
  might be blocked or not at the discretion of browser vendors;
- *active content*, i.e., the rest: must always be blocked.

** CSP to TLS enforcement
CSP provides support to simplify a full transition from HTTP to HTTPS:
1) *upgrade-insecure-requests*: all the HTTP requests sent from the web page are
   automatically upgraded to HTTPS before they are sent on the network. This is
   useful to enforce HTTPS upgrade also for blockable content;
2) *block-all-mixed-content* (now obsoleted): tells the browser that all types of
   mixed content must be blocked. Ignored in modern browsers, because
   upgradeable content is automatically loaded using HTTPS and blockable content
   is already blocked

** HTTP Strict Transport Security (HSTS)
HSTS is a security policy which can be used to prevent SSL stripping:
- HSTS instructs the browser that the server only wants to accept HTTPS
  connections for a given duration;
- The browser must upgrade all the HTTP requests to the server over HTTPS before
  they are sent on the network
- If the security of the HTTPS connection cannot be established, e.g., invalid
  TLS certificate, the browser must stop the connection.

*Strict-Transport-Security: max-age=31536000*

HSTS headers must be honored by the browser only when they are served over HTTPS.

*** HSTS and cookie security

#+begin_quote
*Cookie confidentiality*: Cookies with the Domain attribute can inadvertently be
 shared with HTTP sub-domains. Communication with such domains can be forced by
 network attackers.
#+end_quote


#+begin_quote
*Cookie integrity*: Network attackers can abuse HTTP traffic from sub-domains to
 forge cookies with the Domain attribute, which may be eventually sent to the
 target host.
#+end_quote

*** includeSubDomains option
HSTS can be activated with the *includeSubDomains* option to extend the HTTPS
upgrade to sub-domains as well.

#+begin_quote
*Cookie confidentiality*: Since sub-domains cannot be contacted over HTTP, even
 domain cookies are guaranteed to always be sent over HTTPS.
#+end_quote

#+begin_quote
*Cookie integrity*: Since sub-domains cannot be contacted over HTTP, network
 attackers cannot forge HTTP traffic to set domain cookies.
#+end_quote

*** HSTS Preload list
To simplify HSTS deployment, site operators can ask for inclusion in the HSTS
preload list, i.e., a *list of known HSTS domains that browsers will honor*.
Connections to such domains are subject to strong HSTS policies.

#+begin_quote
*Requirements*:
- Serve a valid certificate;
- Redirect from HTTP to HTTPS on the same host;
- Serve all sub-domains over HTTPS;
- Serve an HSTS header on the base domain for HTTPS requests, with max-age set
  to at least 1 year and includeSubDomains;
- The HSTS policy must include the preload option.
#+end_quote
